%YAML 1.1
---
outputs:
- fast:
    append: true
    enabled: true
    filename: fast.log
- eve-log:
    enabled: true
    filename: /Users/ani/workspace/practicum-cs6727/anzu/anzu/suricata/sock
    filetype: unix_stream
    types:
    - alert:
        payload: true
        payload-buffer-size: 4kb
        payload-printable: true
